### ISSUE TITLE
Light Switch Error

### ISSUE THREAD

**Issue by TAGAPAW** [machin3io/MACHIN3tools#1]
![2017-04-20_171242](https://cloud.githubusercontent.com/assets/26641395/25225826/02488fa2-25ed-11e7-9895-187ce53cfb7d.png)

I'm using 2.78a

**Comment by machin3io** [comment]
Sorry for the delay, I've removed the light switch for now until I find a good way to access the loaded themes in blender via python.

If you want it to work, you need to edit the script and just replace the them path strings, with the location of the themes you want to switch between. It's the 'home/%USERNAME....' lines.
