### ISSUE TITLE
Cant Be Enabled

### ISSUE THREAD

**Issue by TAGAPAW** [machin3io/MACHIN3tools#5]
Sorry for asking again, is there path should be edited or else ? thx in advanced
![teamviewer_2018-05-12_09-17-42](https://user-images.githubusercontent.com/26641395/39952669-5e31e020-55c6-11e8-8924-43a4f1aa321e.png)
![blender_2018-05-12_09-19-59](https://user-images.githubusercontent.com/26641395/39952670-5e63227a-55c6-11e8-8b54-5421c438f926.png)

i'm using 2.79b

**Comment by NiGeL666** [comment]
I have the exact same issue.  I d/l cloned zip, extract "MACHIN3tools-master" to /scripts/addons, went to "user prefs / addons" and the error appears when trying to enable the plugin.  Using latest stable Blender 2.79 release.

**Comment by Esindesign** [comment]
Same issue here aswell

**Comment by machin3io** [comment]
Sorry about that. Please update to the latest release for 2.80.
